### ISSUE TITLE
Crash on open from home

### ISSUE THREAD

**Issue by licaon-kter** [M66B/open-source-email#39]
0.11 on Oreo

Steps
* Open app
* Press home (KISS launcher)
* Press Fairemail icon
* Nothing happens
* Press again...new compose bug report with:

```
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceStatejava.lang.IllegalStateException: Can not perform this action after onSaveInstanceState	at androidx.i.a.j.F(SourceFile:2091)	at androidx.i.a.j.a(SourceFile:2117)	at androidx.i.a.j.a(SourceFile:832)	at eu.faircode.email.ActivityView.onNewIntent(SourceFile:284)	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1313)	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1325)	at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:3361)	at android.app.ActivityThread.performNewIntents(ActivityThread.java:3376)	at android.app.ActivityThread.handleNewIntent(ActivityThread.java:3392)	at android.app.ActivityThread.-wrap15(Unknown Source:0)	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1964)	at android.os.Handler.dispatchMessage(Handler.java:108)	at android.os.Looper.loop(Looper.java:166)	at android.app.ActivityThread.main(ActivityThread.java:7406)	at java.lang.reflect.Method.invoke(Native Method)	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:926)
```  
* Press delete draft to use the app as usual

But, switching to the app in the Taskmanager works ok.

**Comment by M66B** [comment]
Can you please try if the new build fixes the problem?

https://email.faircode.eu/FairEmail-v0.11-release.apk

**Comment by licaon-kter** [comment]
Mmnope

```
 java.lang.IllegalStateException: Can not perform this action after onSaveInstanceStatejava.lang.IllegalStateException: Can not perform this action after onSaveInstanceState	at androidx.i.a.j.E(SourceFile:2080)	at androidx.i.a.j.a(SourceFile:2106)	at androidx.i.a.j.a(SourceFile:832)	at eu.faircode.email.ActivityView.onNewIntent(SourceFile:284)	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1313)	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1325)	at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:3361)	at android.app.ActivityThread.performNewIntents(ActivityThread.java:3376)	at android.app.ActivityThread.handleNewIntent(ActivityThread.java:3392)	at android.app.ActivityThread.-wrap15(Unknown Source:0)	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1964)	at android.os.Handler.dispatchMessage(Handler.java:108)	at android.os.Looper.loop(Looper.java:166)	at android.app.ActivityThread.main(ActivityThread.java:7406)	at java.lang.reflect.Method.invoke(Native Method)	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:926)
```

**Comment by M66B** [comment]
I cannot reproduce this crash, so it must be something device specific. I am going to look for a workaround.

**Comment by licaon-kter** [comment]
Huawei Mate 9 here, both KISS and the stock launcher

**Comment by M66B** [comment]
Can you please confirm that this version fixes the problem?

https://email.faircode.eu/FairEmail-v0.12-release.apk

**Comment by M66B** [comment]
This version is newer: https://github.com/M66B/open-source-email/releases/tag/0.12
